[tool.ruff]
line-length = 100

[tool.ruff.lint]
select=["ALL"]
extend-ignore=["ANN", "D", "FBT", "PLR"]
ignore=[
    "C901",
    "COM812",
    "E501", "E721",
    "EM102",
    "FA102",
    "G004",
    "PD901",
    "PERF401",
    "PLR2004",
    "PLW2901",
    "RUF003",
    "S101", "S602",
    "T201",
    "TRY003",
]
